### ISSUE TITLE
[Feature] Improve the footer of the landing page

### ISSUE THREAD

**Issue by ArnabChatterjee20k** [DevSoc-Asansol2023/DevSoc-Main#1]
Improve the footer of the landing page by enhancing its styling and making it responsive

**Comment by Cstrp** [comment]
I can do it

**Comment by ArnabChatterjee20k** [comment]
Already an issue is assigned to you

**Comment by Cstrp** [comment]
> Already an issue is assigned to you

A, okay. Can i take another one? or i need complete to complete previous task?

**Comment by Baburao-sanivada** [comment]
Can I Work on This Issue?

**Comment by rituraj12797** [comment]
i want to contribute to this issue and this will help me in learning and contributing with the team
@ArnabChatterjee20k .
please assign this issue to me

**Comment by ArnabChatterjee20k** [comment]
I am this issue to @Baburao-sanivada as he asked first
Before raising the pr please read the contributing guidelines and attach a screenshot with the pr
Also update us within every 3days

**Comment by Baburao-sanivada** [comment]
@ArnabChatterjee20k I raised a PR Could you Verify It?

**Comment by Baburao-sanivada** [comment]
Hii Bro I Could Find what the Conflict is ? Can You Help me to How To create a New Pull Request?

**Comment by ArnabChatterjee20k** [comment]
> Hii Bro I Could Find what the Conflict is ? Can You Help me to How To create a New Pull Request?

Sorry I was inactive. I hope you solved that merging issue

**Comment by ArnabChatterjee20k** [comment]
> @ArnabChatterjee20k Could you Please Check the New PR?

merged
