### ISSUE TITLE
[Feature] Design a event management ui using figma

### ISSUE THREAD

**Issue by ArnabChatterjee20k** [DevSoc-Asansol2023/DevSoc-Main#10]
Our current ui - [Figma link](https://www.figma.com/file/TrCThPaNbMacGFuGIyksuu/DevSoc-AEC-HacktoberFest?type=design&node-id=0-1&mode=design&t=udIGSajvmYi0neBn-0)

### Add a event management ui having the following details.

For inspiration you can use this - [Inspiration UI link](https://dribbble.com/shots/14652396-Meeting-App-UI)
But the color system should match our color scheme

- [ ]  A calendar showing dates and list of cards showing the event brief.
- [ ]  Individual event page when clicked on the event cards. It will contain event details(blog like design). And a register button
- [ ] Calendar should have some markings.

### Guidelines
* Create a new branch
* Please make a folder design
* Download the your ui and make a pr by uploading the file

**Comment by widewipe** [comment]
I want to give this a try. Can you explain what details to show on the event details page?

**Comment by ArnabChatterjee20k** [comment]
@widewipe please follow the ui links given and the guidelines given in the issue. You can ask your doubts in this section only.
About file - 
* Make a figma file
* Check the inspiration links given and design that accordingly and kept the color schemes aligned with our design system
* After you completed your design , download the figma file as .fig file
* Create a folder "design"
* Move that .fig file in that design folder
* Make the pr along with the screenshot of the ui

**Comment by widewipe** [comment]
Can I use both the purple and orange colors for the UI?

**Comment by widewipe** [comment]
I have completed the UI for the events section, I will now work on the individual event page and make a PR as soon as I can.

**Comment by ArnabChatterjee20k** [comment]
Please share the ui you have done here for an early review

**Comment by widewipe** [comment]
This is the Events section I worked on.
![image](https://github.com/DevSoc-Asansol2023/DevSoc-Main/assets/132732400/535b90a2-76ad-49c4-a544-a201df0eeab0)

**Comment by ArnabChatterjee20k** [comment]
Looking nice
Make the mobile view as well

**Comment by widewipe** [comment]
I have completed the designs.
Here are the screenshots, do say so in case of any improvements.

### This is the mobile version of the events section UI.
![Screenshot from 2023-10-08 17-07-25](https://github.com/DevSoc-Asansol2023/DevSoc-Main/assets/132732400/cc7db109-a58b-4fa8-b48d-51c67bffcd79)


### UI of individual event page with event details and registration/joining button.
![Screenshot from 2023-10-08 17-06-40](https://github.com/DevSoc-Asansol2023/DevSoc-Main/assets/132732400/9f313736-03a4-4efc-905f-53a033b93649)

### Individual event page UI in mobile version.
![image](https://github.com/DevSoc-Asansol2023/DevSoc-Main/assets/132732400/b5b28187-516d-43fd-9588-5d81df11bdda)

**Comment by ArnabChatterjee20k** [comment]
Thanks @widewipe for preparing such nice uis. You can download them locally as .fig file and upload the way I have mentioned in the issue

**Comment by ArnabChatterjee20k** [comment]
@widewipe any updates?

**Comment by widewipe** [comment]
@ArnabChatterjee20k I have already made the pull request for this issue.

**Comment by ArnabChatterjee20k** [comment]
yes yes
Actually I thought you would comment here
Thanks @widewipe for your contribution
I will review it
