### ISSUE TITLE
[Feature] Profile Section of the logged in user

### ISSUE THREAD

**Issue by ArnabChatterjee20k** [DevSoc-Asansol2023/DevSoc-Main#12]
Our current ui - [Figma link](https://www.figma.com/file/TrCThPaNbMacGFuGIyksuu/DevSoc-AEC-HacktoberFest?type=design&node-id=0-1&mode=design&t=udIGSajvmYi0neBn-0)

Reference the user profile frame
![image](https://github.com/DevSoc-Asansol2023/DevSoc-Main/assets/83803257/3db8a85c-eacb-4045-aadb-93d8e2a65869)

For more reference visit the figma file

- [ ] Implement the user profile system to track the user's participation in various events using horizontal cards(use dummy data)

### Guidelines
* Can change the design and make it better.
* If any design update is made please upload it inside the folder design
* Code quality matters
* Attach a video or video link showing the ui of the profile section

**Comment by jgyfutub** [comment]
Can I take this issue?

**Comment by ArnabChatterjee20k** [comment]
@jgyfutub I am assigning the issue to you
Please keep updating us within every 3days

**Comment by jgyfutub** [comment]
@ArnabChatterjee20k can you please tell how shall I put stars in the background?
