### ISSUE TITLE
UI  feature and fix : Nav Bar

### ISSUE THREAD

**Issue by VarunCypherV** [DevSoc-Asansol2023/DevSoc-Main#13]
Feature : On Hover : A Line and Colour change to the yellow of the Devsoc will be a better design view
Fix : Alignment of the Nav bar to the content , better design principle

![image](https://github.com/DevSoc-Asansol2023/DevSoc-Main/assets/91377728/591f667e-97c0-4c6b-af0a-be49010b79dc)

**Comment by Baburao-sanivada** [comment]
hey @VarunCypherV can i Work on this Issue?

**Comment by VarunCypherV** [comment]
I have already created an PR for this , but view their website , you can add a lot to it

**Comment by Baburao-sanivada** [comment]
ok bro

**Comment by ArnabChatterjee20k** [comment]
@VarunCypherV thanks for your concern and contribution
But in our guidelines it is clearly written that before making any pr please make it assigned to you.  Please keep in mind from next time.

**Comment by VarunCypherV** [comment]
Sorry about that , sure from next time , thank you!
