### ISSUE TITLE
Create the bottom to top arrow

### ISSUE THREAD

**Issue by Arnabhit** [DevSoc-Asansol2023/DevSoc-Main#18]
Hello there I want to add the bottom to top arrow in your website. please assign this issue to me under hacktoberfest

**Comment by ArnabChatterjee20k** [comment]
Thank you @Arnabhit for your interest
I am assigning this to you
Please maintain the color scheme

**Comment by Arnabhit** [comment]
Can you please add the hacktoberfest label

**Comment by ArnabChatterjee20k** [comment]
Added
