### ISSUE TITLE
[Feature] Improve the navbar

### ISSUE THREAD

**Issue by ArnabChatterjee20k** [DevSoc-Asansol2023/DevSoc-Main#2]
Improve the navbar by fixing its style and make it responsive in all devices

**Comment by Ritish134** [comment]
hi there, excited to contribute can you assign me

**Comment by ArnabChatterjee20k** [comment]
Hi @Ritish134 I am assigning it you. Please try updating us every 3 days.

**Comment by Ritish134** [comment]
ok

**Comment by Ritish134** [comment]
![popup_menu](https://github.com/DevSoc-Asansol2023/DevSoc-Main/assets/121374890/d2b32101-befd-4721-9a6d-c6b2d24f738b)
Added popup menu for smaller screens.

**Comment by Prithiraj12345** [comment]
I am interested to take the issue plzz assign me this issue
