### ISSUE TITLE
[Feature] Adding an automation for issues

### ISSUE THREAD

**Issue by Akib-Vijapura** [DevSoc-Asansol2023/DevSoc-Main#26]
Whenever a contributor creates an issue, they have the option to select an issue type such as bug, documentation update, feature request, or style change request. Based on their chosen issue type, an appropriate template will be automatically generated for that issue.

**Comment by Akib-Vijapura** [comment]
I am eager and willing to work on this issue.

**Comment by ArnabChatterjee20k** [comment]
@Akib-Vijapura I am assigning this you
