### ISSUE TITLE
fixing Horizontal scroll bar issue 

### ISSUE THREAD

**Issue by Ayusht777** [DevSoc-Asansol2023/DevSoc-Main#29]
hey i see Horizontal scroll bar in your website which cause various ui issue so i want to fix it

**Comment by ArnabChatterjee20k** [comment]
@Ayusht777 I am assigning this issue to you

**Comment by Ayusht777** [comment]
fix it and also any another issue's

**Comment by ArnabChatterjee20k** [comment]
Can you fix the navbar as well? You can change the issue title accordingly

**Comment by Ayusht777** [comment]
okay let see
