### ISSUE TITLE
[Bug] Hero Section is not responsive

### ISSUE THREAD

**Issue by ArnabChatterjee20k** [DevSoc-Asansol2023/DevSoc-Main#3]
The hero section is breaking in devices smaller than desktop.

**Comment by Cstrp** [comment]
U can assigned this for me)

**Comment by ArnabChatterjee20k** [comment]
Hi @Cstrp I assigned the issue to you. Try updating us in every 3days

**Comment by Cstrp** [comment]
> Hi @Cstrp I assigned the issue to you. Try updating us in every 3days

Okay :)
