### ISSUE TITLE
[Bug] FIx the ui and responsiveness of the call to action section

### ISSUE THREAD

**Issue by ArnabChatterjee20k** [DevSoc-Asansol2023/DevSoc-Main#5]
![image](https://github.com/DevSoc-Asansol2023/DevSoc-Main/assets/83803257/d1e7d0ea-4614-4bee-af93-0b8cde927301)
![image](https://github.com/DevSoc-Asansol2023/DevSoc-Main/assets/83803257/88469fb3-329a-4bae-9784-197ab54afd55)

Make it according to our design file https://www.figma.com/file/C1xLyZe2wvYVFdusEHRVGZ/DevSoc?type=design&node-id=0-1&mode=design&t=TAnWT775AtPhgUuM-0

These components are having responsiveness issues in smaller devices.

**Comment by vedika-gupta** [comment]
Please assign this issue to me.

**Comment by ArnabChatterjee20k** [comment]
@vedika-gupta I assigned the issue to you
Please update us within every 3days
