### ISSUE TITLE
[Feature] Adding an automation of issuing a pr template

### ISSUE THREAD

**Issue by ArnabChatterjee20k** [DevSoc-Asansol2023/DevSoc-Main#6]
Whenever the contributor will raise a pr he needs to fill certain criteria.
So a template will be automatically added in the comment section with the following fields
```
Issue id 
Previous issue
Screenshots/video/urls
```

**Comment by Akib-Vijapura** [comment]
Hey, I want to work on this issue.

**Comment by ArnabChatterjee20k** [comment]
I am assigning this issue to @Akib-Vijapura 
Please keep updating us within every 3days
